import { useMemo } from "react";

export function useGameSessionProps({
  mode,
  goHome,
  lang,
  score,
  totalPossible,
  timeLeft,
  handleHudEnter,
  isPlaying,
  isGameOver,
  handleCustomConfirm,
  stopGame,
  t,
  setShowInfoModal,
  selectedCountry,
  setSelectedCountry,
  resetNavigationTrail,
  navigateFocus,
  popupError,
  popupWarning,
  popupSuccess,
  extInputRef,
  foundList,
  activeDataMap,
  theme,
  viewport,
  isKeyboardMode,
  globeTheme,
  learnSubMode,
  onLearnSubModeChange,
  learnSearchQuery,
  setLearnSearchQuery,
  setShowLearnPanel,
  showLearnPanel,
  isMobileViewport,
  countriesData,
  departmentsData,
  handleCountrySelect,
  perfProfile,
  currentScreen,
  showEndScreen,
  preserveInputFocus,
  countryDataMap,
  setShowEndScreen,
  setShowResultsTable,
  lastScores,
  localRecords,
  isNewPB,
  xpResult,
  isPanelOpen,
  closePanel,
  panelDataMap,
  handlePanelSelect,
  panelMode,
  showResultsTable,
  globeFeedbackRef,
  globeFeedbackApplierRef,
  livesLeft,
  isHardcoreRun,
}) {
  return useMemo(
    () => ({
      hudProps: {
        mode,
        onGoHome: goHome,
        lang,
        score,
        totalPossible,
        timeLeft,
        onEnter: handleHudEnter,
        isPlaying,
        isGameOver,
        onStop: () => handleCustomConfirm(t("stop_game_confirm"), stopGame),
        onInfo: () => setShowInfoModal(true),
        isFocusedCountry: Boolean(selectedCountry),
        onClearFocus: () => {
          setSelectedCountry(null);
          resetNavigationTrail(null);
        },
        onNavigateFocus: navigateFocus,
        inputError: popupError,
        inputWarning: popupWarning,
        inputSuccess: popupSuccess,
        extInputRef,
        foundList,
        countryDataMap: activeDataMap,
        theme,
        viewport,
        isKeyboardMode,
        selectedCountry,
        globeTheme,
        learnSearchQuery,
        onLearnSearchChange: setLearnSearchQuery,
        onToggleLearnPanel: () => setShowLearnPanel((v) => !v),
        showLearnPanel,
        hideLearnInput: mode === "learn" && !isMobileViewport,
        isPanelOpen: isPanelOpen && mode !== "learn",
        hideHudPlayStop: isPanelOpen && mode !== "learn",
        livesLeft,
        isHardcoreRun,
      },
      globeProps: {
        mode,
        lang,
        countriesData,
        departmentsData,
        foundList,
        selectedCountry,
        shouldAutoRotate: false,
        onCountrySelect: handleCountrySelect,
        theme,
        viewport,
        isError: popupError,
        isSuccess: popupSuccess,
        hasActiveFeedback: popupError || popupSuccess,
        perfProfile,
        isHomeScreen: currentScreen === "home",
        isKeyboardMode,
        isEndScreen: currentScreen === "game" && showEndScreen,
        isPerfectScore: foundList.length === totalPossible,
        onPreserveInputFocus: preserveInputFocus,
        activeDataMap,
        globeTheme,
        learnSubMode,
        globeFeedbackRef,
        globeFeedbackApplierRef,
      },
      endScreenProps: {
        foundList,
        totalCountries: totalPossible,
        countryDataMap,
        activeDataMap,
        onRestart: goHome,
        onViewTable: () => {
          setShowEndScreen(false);
          setShowResultsTable(true);
        },
        theme,
        lang,
        globeTheme,
        lastScores: lastScores[mode] || [],
        maxScore: localRecords[mode]?.maxScore || 0,
        isNewPB,
        xpResult,
        livesLeft,
        isHardcoreRun,
      },
      panelProps: {
        dataMap: panelDataMap,
        foundList,
        selectedCountry,
        onSelectCountry: handlePanelSelect,
        onClose: mode !== "learn" || isMobileViewport ? closePanel : undefined,
        onGoHome: isGameOver ? goHome : undefined,
        mode: panelMode,
        theme,
        lang,
        globeTheme,
        isGameOver: isGameOver && showResultsTable,
        revealAll: mode === "learn" || (isGameOver && showResultsTable),
        variant: showResultsTable && isGameOver ? "overlay" : "side",
        score: foundList.length,
        total: totalPossible,
        searchQuery: mode === "learn" ? learnSearchQuery : undefined,
        onSearchChange: mode === "learn" ? setLearnSearchQuery : undefined,
        showSearch: mode === "learn",
        isLearnMode: mode === "learn",
        learnSubMode: mode === "learn" ? learnSubMode : undefined,
        onLearnSubModeChange: mode === "learn" ? onLearnSubModeChange : undefined,
        allowDeselect: !isMobileViewport,
      },
      showHud: currentScreen === "game" && !showEndScreen,
      showEndScreen: currentScreen === "game" && showEndScreen,
      gamePanelOpen: currentScreen === "game" && isPanelOpen,
    }),
    [
      mode,
      goHome,
      lang,
      score,
      totalPossible,
      timeLeft,
      handleHudEnter,
      isPlaying,
      isGameOver,
      handleCustomConfirm,
      stopGame,
      t,
      setShowInfoModal,
      selectedCountry,
      setSelectedCountry,
      resetNavigationTrail,
      navigateFocus,
      popupError,
      popupWarning,
      popupSuccess,
      extInputRef,
      foundList,
      activeDataMap,
      theme,
      viewport,
      isKeyboardMode,
      globeTheme,
      learnSubMode,
      onLearnSubModeChange,
      learnSearchQuery,
      setLearnSearchQuery,
      setShowLearnPanel,
      showLearnPanel,
      isMobileViewport,
      countriesData,
      departmentsData,
      handleCountrySelect,
      perfProfile,
      currentScreen,
      showEndScreen,
      preserveInputFocus,
      countryDataMap,
      setShowEndScreen,
      setShowResultsTable,
      lastScores,
      localRecords,
      isNewPB,
      xpResult,
      isPanelOpen,
      closePanel,
      panelDataMap,
      handlePanelSelect,
      panelMode,
      showResultsTable,
      globeFeedbackRef,
      globeFeedbackApplierRef,
      livesLeft,
      isHardcoreRun,
    ]
  );
}
