export const departmentsDataMap = {
  "01": { code: "01", name_fr: "Ain", name_en: "Ain", capital_fr: "Bourg-en-Bresse", capital: "Bourg-en-Bresse", lat: 46.2044, lng: 5.2258, region: "France" },
  "02": { code: "02", name_fr: "Aisne", name_en: "Aisne", capital_fr: "Laon", capital: "Laon", lat: 49.5639, lng: 3.6244, region: "France" },
  "03": { code: "03", name_fr: "Allier", name_en: "Allier", capital_fr: "Moulins", capital: "Moulins", lat: 46.3402, lng: 3.4307, region: "France" },
  "04": { code: "04", name_fr: "Alpes-de-Haute-Provence", name_en: "Alpes-de-Haute-Provence", capital_fr: "Digne-les-Bains", capital: "Digne-les-Bains", lat: 44.0920, lng: 6.2350, region: "France" },
  "05": { code: "05", name_fr: "Hautes-Alpes", name_en: "Hautes-Alpes", capital_fr: "Gap", capital: "Gap", lat: 44.5596, lng: 6.0798, region: "France" },
  "06": { code: "06", name_fr: "Alpes-Maritimes", name_en: "Alpes-Maritimes", capital_fr: "Nice", capital: "Nice", lat: 43.7102, lng: 7.2620, region: "France" },
  "07": { code: "07", name_fr: "Ardèche", name_en: "Ardeche", capital_fr: "Privas", capital: "Privas", lat: 44.7353, lng: 4.5990, region: "France" },
  "08": { code: "08", name_fr: "Ardennes", name_en: "Ardennes", capital_fr: "Charleville-Mézières", capital: "Charleville-Mézières", lat: 49.7621, lng: 4.7247, region: "France" },
  "09": { code: "09", name_fr: "Ariège", name_en: "Ariege", capital_fr: "Foix", capital: "Foix", lat: 42.9639, lng: 1.6054, region: "France" },
  "10": { code: "10", name_fr: "Aube", name_en: "Aube", capital_fr: "Troyes", capital: "Troyes", lat: 48.2973, lng: 4.0744, region: "France" },
  "11": { code: "11", name_fr: "Aude", name_en: "Aude", capital_fr: "Carcassonne", capital: "Carcassonne", lat: 43.2130, lng: 2.3491, region: "France" },
  "12": { code: "12", name_fr: "Aveyron", name_en: "Aveyron", capital_fr: "Rodez", capital: "Rodez", lat: 44.3494, lng: 2.5759, region: "France" },
  "13": { code: "13", name_fr: "Bouches-du-Rhône", name_en: "Bouches-du-Rhone", capital_fr: "Marseille", capital: "Marseille", lat: 43.2965, lng: 5.3698, region: "France" },
  "14": { code: "14", name_fr: "Calvados", name_en: "Calvados", capital_fr: "Caen", capital: "Caen", lat: 49.1829, lng: -0.3707, region: "France" },
  "15": { code: "15", name_fr: "Cantal", name_en: "Cantal", capital_fr: "Aurillac", capital: "Aurillac", lat: 44.9300, lng: 2.4440, region: "France" },
  "16": { code: "16", name_fr: "Charente", name_en: "Charente", capital_fr: "Angoulême", capital: "Angoulême", lat: 45.6484, lng: 0.1562, region: "France" },
  "17": { code: "17", name_fr: "Charente-Maritime", name_en: "Charente-Maritime", capital_fr: "La Rochelle", capital: "La Rochelle", lat: 46.1603, lng: -1.1511, region: "France" },
  "18": { code: "18", name_fr: "Cher", name_en: "Cher", capital_fr: "Bourges", capital: "Bourges", lat: 47.0810, lng: 2.3988, region: "France" },
  "19": { code: "19", name_fr: "Corrèze", name_en: "Correze", capital_fr: "Tulle", capital: "Tulle", lat: 45.2670, lng: 1.7707, region: "France" },
  "2A": { code: "2A", name_fr: "Corse-du-Sud", name_en: "Corse-du-Sud", capital_fr: "Ajaccio", capital: "Ajaccio", aliases: ["corse du sud"], lat: 41.9267, lng: 8.7369, region: "France" },
  "2B": { code: "2B", name_fr: "Haute-Corse", name_en: "Haute-Corse", capital_fr: "Bastia", capital: "Bastia", aliases: ["haute corse"], lat: 42.6973, lng: 9.4509, region: "France" },
  "21": { code: "21", name_fr: "Côte-d'Or", name_en: "Cote-d'Or", capital_fr: "Dijon", capital: "Dijon", aliases: ["cote d or"], lat: 47.3220, lng: 5.0415, region: "France" },
  "22": { code: "22", name_fr: "Côtes-d'Armor", name_en: "Cotes-d'Armor", capital_fr: "Saint-Brieuc", capital: "Saint-Brieuc", aliases: ["cotes d armor"], lat: 48.5142, lng: -2.7658, region: "France" },
  "23": { code: "23", name_fr: "Creuse", name_en: "Creuse", capital_fr: "Guéret", capital: "Guéret", lat: 46.1707, lng: 1.8713, region: "France" },
  "24": { code: "24", name_fr: "Dordogne", name_en: "Dordogne", capital_fr: "Périgueux", capital: "Périgueux", lat: 45.1840, lng: 0.7210, region: "France" },
  "25": { code: "25", name_fr: "Doubs", name_en: "Doubs", capital_fr: "Besançon", capital: "Besançon", lat: 47.2378, lng: 6.0241, region: "France" },
  "26": { code: "26", name_fr: "Drôme", name_en: "Drome", capital_fr: "Valence", capital: "Valence", lat: 44.9334, lng: 4.8924, region: "France" },
  "27": { code: "27", name_fr: "Eure", name_en: "Eure", capital_fr: "Évreux", capital: "Évreux", lat: 49.0270, lng: 1.1514, region: "France" },
  "28": { code: "28", name_fr: "Eure-et-Loir", name_en: "Eure-et-Loir", capital_fr: "Chartres", capital: "Chartres", lat: 48.4439, lng: 1.4890, region: "France" },
  "29": { code: "29", name_fr: "Finistère", name_en: "Finistere", capital_fr: "Quimper", capital: "Quimper", lat: 48.3904, lng: -4.4861, region: "France" },
  "30": { code: "30", name_fr: "Gard", name_en: "Gard", capital_fr: "Nîmes", capital: "Nîmes", lat: 43.8367, lng: 4.3601, region: "France" },
  "31": { code: "31", name_fr: "Haute-Garonne", name_en: "Haute-Garonne", capital_fr: "Toulouse", capital: "Toulouse", lat: 43.6047, lng: 1.4442, region: "France" },
  "32": { code: "32", name_fr: "Gers", name_en: "Gers", capital_fr: "Auch", capital: "Auch", lat: 43.6464, lng: 0.5867, region: "France" },
  "33": { code: "33", name_fr: "Gironde", name_en: "Gironde", capital_fr: "Bordeaux", capital: "Bordeaux", lat: 44.8378, lng: -0.5792, region: "France" },
  "34": { code: "34", name_fr: "Hérault", name_en: "Herault", capital_fr: "Montpellier", capital: "Montpellier", lat: 43.6108, lng: 3.8767, region: "France" },
  "35": { code: "35", name_fr: "Ille-et-Vilaine", name_en: "Ille-et-Vilaine", capital_fr: "Rennes", capital: "Rennes", lat: 48.1173, lng: -1.6778, region: "France" },
  "36": { code: "36", name_fr: "Indre", name_en: "Indre", capital_fr: "Châteauroux", capital: "Châteauroux", lat: 46.8097, lng: 1.6911, region: "France" },
  "37": { code: "37", name_fr: "Indre-et-Loire", name_en: "Indre-et-Loire", capital_fr: "Tours", capital: "Tours", lat: 47.3941, lng: 0.6848, region: "France" },
  "38": { code: "38", name_fr: "Isère", name_en: "Isere", capital_fr: "Grenoble", capital: "Grenoble", lat: 45.1885, lng: 5.7245, region: "France" },
  "39": { code: "39", name_fr: "Jura", name_en: "Jura", capital_fr: "Lons-le-Saunier", capital: "Lons-le-Saunier", lat: 46.6753, lng: 5.5537, region: "France" },
  "40": { code: "40", name_fr: "Landes", name_en: "Landes", capital_fr: "Mont-de-Marsan", capital: "Mont-de-Marsan", lat: 43.8900, lng: -0.5000, region: "France" },
  "41": { code: "41", name_fr: "Loir-et-Cher", name_en: "Loir-et-Cher", capital_fr: "Blois", capital: "Blois", lat: 47.5861, lng: 1.3359, region: "France" },
  "42": { code: "42", name_fr: "Loire", name_en: "Loire", capital_fr: "Saint-Étienne", capital: "Saint-Étienne", lat: 45.4397, lng: 4.3872, region: "France" },
  "43": { code: "43", name_fr: "Haute-Loire", name_en: "Haute-Loire", capital_fr: "Le Puy-en-Velay", capital: "Le Puy-en-Velay", lat: 45.0439, lng: 3.8850, region: "France" },
  "44": { code: "44", name_fr: "Loire-Atlantique", name_en: "Loire-Atlantique", capital_fr: "Nantes", capital: "Nantes", lat: 47.2184, lng: -1.5536, region: "France" },
  "45": { code: "45", name_fr: "Loiret", name_en: "Loiret", capital_fr: "Orléans", capital: "Orléans", lat: 47.9029, lng: 1.9093, region: "France" },
  "46": { code: "46", name_fr: "Lot", name_en: "Lot", capital_fr: "Cahors", capital: "Cahors", lat: 44.4475, lng: 1.4419, region: "France" },
  "47": { code: "47", name_fr: "Lot-et-Garonne", name_en: "Lot-et-Garonne", capital_fr: "Agen", capital: "Agen", lat: 44.2031, lng: 0.6164, region: "France" },
  "48": { code: "48", name_fr: "Lozère", name_en: "Lozere", capital_fr: "Mende", capital: "Mende", lat: 44.5180, lng: 3.5000, region: "France" },
  "49": { code: "49", name_fr: "Maine-et-Loire", name_en: "Maine-et-Loire", capital_fr: "Angers", capital: "Angers", lat: 47.4784, lng: -0.5632, region: "France" },
  "50": { code: "50", name_fr: "Manche", name_en: "Manche", capital_fr: "Saint-Lô", capital: "Saint-Lô", lat: 49.1156, lng: -1.0900, region: "France" },
  "51": { code: "51", name_fr: "Marne", name_en: "Marne", capital_fr: "Châlons-en-Champagne", capital: "Châlons-en-Champagne", lat: 49.2583, lng: 4.0317, region: "France" },
  "52": { code: "52", name_fr: "Haute-Marne", name_en: "Haute-Marne", capital_fr: "Chaumont", capital: "Chaumont", lat: 48.1113, lng: 5.1390, region: "France" },
  "53": { code: "53", name_fr: "Mayenne", name_en: "Mayenne", capital_fr: "Laval", capital: "Laval", lat: 48.0686, lng: -0.7669, region: "France" },
  "54": { code: "54", name_fr: "Meurthe-et-Moselle", name_en: "Meurthe-et-Moselle", capital_fr: "Nancy", capital: "Nancy", lat: 48.6921, lng: 6.1844, region: "France" },
  "55": { code: "55", name_fr: "Meuse", name_en: "Meuse", capital_fr: "Bar-le-Duc", capital: "Bar-le-Duc", lat: 49.1590, lng: 5.3820, region: "France" },
  "56": { code: "56", name_fr: "Morbihan", name_en: "Morbihan", capital_fr: "Vannes", capital: "Vannes", lat: 47.6582, lng: -2.7608, region: "France" },
  "57": { code: "57", name_fr: "Moselle", name_en: "Moselle", capital_fr: "Metz", capital: "Metz", lat: 49.1193, lng: 6.1757, region: "France" },
  "58": { code: "58", name_fr: "Nièvre", name_en: "Nievre", capital_fr: "Nevers", capital: "Nevers", lat: 46.9896, lng: 3.1590, region: "France" },
  "59": { code: "59", name_fr: "Nord", name_en: "Nord", capital_fr: "Lille", capital: "Lille", lat: 50.6292, lng: 3.0573, region: "France" },
  "60": { code: "60", name_fr: "Oise", name_en: "Oise", capital_fr: "Beauvais", capital: "Beauvais", lat: 49.4300, lng: 2.0800, region: "France" },
  "61": { code: "61", name_fr: "Orne", name_en: "Orne", capital_fr: "Alençon", capital: "Alençon", lat: 48.4329, lng: 0.0913, region: "France" },
  "62": { code: "62", name_fr: "Pas-de-Calais", name_en: "Pas-de-Calais", capital_fr: "Arras", capital: "Arras", lat: 50.2910, lng: 2.7775, region: "France" },
  "63": { code: "63", name_fr: "Puy-de-Dôme", name_en: "Puy-de-Dome", capital_fr: "Clermont-Ferrand", capital: "Clermont-Ferrand", lat: 45.7772, lng: 3.0870, region: "France" },
  "64": { code: "64", name_fr: "Pyrénées-Atlantiques", name_en: "Pyrenees-Atlantiques", capital_fr: "Pau", capital: "Pau", lat: 43.2951, lng: -0.3708, region: "France" },
  "65": { code: "65", name_fr: "Hautes-Pyrénées", name_en: "Hautes-Pyrenees", capital_fr: "Tarbes", capital: "Tarbes", lat: 43.2329, lng: 0.0781, region: "France" },
  "66": { code: "66", name_fr: "Pyrénées-Orientales", name_en: "Pyrenees-Orientales", capital_fr: "Perpignan", capital: "Perpignan", lat: 42.6887, lng: 2.8948, region: "France" },
  "67": { code: "67", name_fr: "Bas-Rhin", name_en: "Bas-Rhin", capital_fr: "Strasbourg", capital: "Strasbourg", lat: 48.5734, lng: 7.7521, region: "France" },
  "68": { code: "68", name_fr: "Haut-Rhin", name_en: "Haut-Rhin", capital_fr: "Colmar", capital: "Colmar", lat: 47.7508, lng: 7.3359, region: "France" },
  "69": { code: "69", name_fr: "Rhône", name_en: "Rhone", capital_fr: "Lyon", capital: "Lyon", lat: 45.7640, lng: 4.8357, region: "France" },
  "70": { code: "70", name_fr: "Haute-Saône", name_en: "Haute-Saone", capital_fr: "Vesoul", capital: "Vesoul", lat: 47.6220, lng: 6.1550, region: "France" },
  "71": { code: "71", name_fr: "Saône-et-Loire", name_en: "Saone-et-Loire", capital_fr: "Mâcon", capital: "Mâcon", lat: 46.3069, lng: 4.8287, region: "France" },
  "72": { code: "72", name_fr: "Sarthe", name_en: "Sarthe", capital_fr: "Le Mans", capital: "Le Mans", lat: 48.0061, lng: 0.1996, region: "France" },
  "73": { code: "73", name_fr: "Savoie", name_en: "Savoie", capital_fr: "Chambéry", capital: "Chambéry", lat: 45.5667, lng: 5.9200, region: "France" },
  "74": { code: "74", name_fr: "Haute-Savoie", name_en: "Haute-Savoie", capital_fr: "Annecy", capital: "Annecy", lat: 45.8992, lng: 6.1294, region: "France" },
  "75": { code: "75", name_fr: "Paris", name_en: "Paris", capital_fr: "Paris", capital: "Paris", lat: 48.8566, lng: 2.3522, region: "France" },
  "76": { code: "76", name_fr: "Seine-Maritime", name_en: "Seine-Maritime", capital_fr: "Rouen", capital: "Rouen", lat: 49.4431, lng: 1.0993, region: "France" },
  "77": { code: "77", name_fr: "Seine-et-Marne", name_en: "Seine-et-Marne", capital_fr: "Melun", capital: "Melun", lat: 48.5400, lng: 2.6600, region: "France" },
  "78": { code: "78", name_fr: "Yvelines", name_en: "Yvelines", capital_fr: "Versailles", capital: "Versailles", lat: 48.8049, lng: 2.1204, region: "France" },
  "79": { code: "79", name_fr: "Deux-Sèvres", name_en: "Deux-Sevres", capital_fr: "Niort", capital: "Niort", lat: 46.3237, lng: -0.4648, region: "France" },
  "80": { code: "80", name_fr: "Somme", name_en: "Somme", capital_fr: "Amiens", capital: "Amiens", lat: 49.8941, lng: 2.2958, region: "France" },
  "81": { code: "81", name_fr: "Tarn", name_en: "Tarn", capital_fr: "Albi", capital: "Albi", lat: 43.9280, lng: 2.1460, region: "France" },
  "82": { code: "82", name_fr: "Tarn-et-Garonne", name_en: "Tarn-et-Garonne", capital_fr: "Montauban", capital: "Montauban", lat: 44.0221, lng: 1.3529, region: "France" },
  "83": { code: "83", name_fr: "Var", name_en: "Var", capital_fr: "Toulon", capital: "Toulon", lat: 43.1242, lng: 5.9280, region: "France" },
  "84": { code: "84", name_fr: "Vaucluse", name_en: "Vaucluse", capital_fr: "Avignon", capital: "Avignon", lat: 43.9493, lng: 4.8055, region: "France" },
  "85": { code: "85", name_fr: "Vendée", name_en: "Vendee", capital_fr: "La Roche-sur-Yon", capital: "La Roche-sur-Yon", lat: 46.6705, lng: -1.4264, region: "France" },
  "86": { code: "86", name_fr: "Vienne", name_en: "Vienne", capital_fr: "Poitiers", capital: "Poitiers", lat: 46.5802, lng: 0.3404, region: "France" },
  "87": { code: "87", name_fr: "Haute-Vienne", name_en: "Haute-Vienne", capital_fr: "Limoges", capital: "Limoges", lat: 45.8336, lng: 1.2611, region: "France" },
  "88": { code: "88", name_fr: "Vosges", name_en: "Vosges", capital_fr: "Épinal", capital: "Épinal", lat: 48.1740, lng: 6.4500, region: "France" },
  "89": { code: "89", name_fr: "Yonne", name_en: "Yonne", capital_fr: "Auxerre", capital: "Auxerre", lat: 47.7982, lng: 3.5738, region: "France" },
  "90": { code: "90", name_fr: "Territoire de Belfort", name_en: "Territoire de Belfort", capital_fr: "Belfort", capital: "Belfort", lat: 47.6379, lng: 6.8629, region: "France" },
  "91": { code: "91", name_fr: "Essonne", name_en: "Essonne", capital_fr: "Évry-Courcouronnes", capital: "Évry-Courcouronnes", lat: 48.6298, lng: 2.4418, region: "France" },
  "92": { code: "92", name_fr: "Hauts-de-Seine", name_en: "Hauts-de-Seine", capital_fr: "Nanterre", capital: "Nanterre", lat: 48.8924, lng: 2.2153, region: "France" },
  "93": { code: "93", name_fr: "Seine-Saint-Denis", name_en: "Seine-Saint-Denis", capital_fr: "Bobigny", capital: "Bobigny", lat: 48.9362, lng: 2.3574, region: "France" },
  "94": { code: "94", name_fr: "Val-de-Marne", name_en: "Val-de-Marne", capital_fr: "Créteil", capital: "Créteil", lat: 48.7904, lng: 2.4556, region: "France" },
  "95": { code: "95", name_fr: "Val-d'Oise", name_en: "Val-d'Oise", capital_fr: "Pontoise", capital: "Pontoise", aliases: ["val d oise"], lat: 49.0500, lng: 2.1000, region: "France" },
  "971": { code: "971", name_fr: "Guadeloupe", name_en: "Guadeloupe", capital_fr: "Basse-Terre", capital: "Basse-Terre", lat: 16.2650, lng: -61.5510, region: "France" },
  "972": { code: "972", name_fr: "Martinique", name_en: "Martinique", capital_fr: "Fort-de-France", capital: "Fort-de-France", lat: 14.6415, lng: -61.0242, region: "France" },
  "973": { code: "973", name_fr: "Guyane", name_en: "French Guiana", capital_fr: "Cayenne", capital: "Cayenne", aliases: ["guyane francaise", "guyane française"], lat: 3.9339, lng: -53.1258, region: "France" },
  "974": { code: "974", name_fr: "La Réunion", name_en: "Reunion", capital_fr: "Saint-Denis", capital: "Saint-Denis", aliases: ["reunion", "réunion"], lat: -21.1151, lng: 55.5364, region: "France" },
  "976": { code: "976", name_fr: "Mayotte", name_en: "Mayotte", capital_fr: "Mamoudzou", capital: "Mamoudzou", lat: -12.8275, lng: 45.1662, region: "France" }
};

export const departmentModeConfig = {
  mode: "departments",
  label: "Départements français",
  shortLabel: "Départements",
  total: Object.keys(departmentsDataMap).length
};
